USE test;
DROP TABLE Category;
-- DESCRIBE Category;
CREATE TABLE category(
    Category_ID INT NOT NULL AUTO_INCREMENT,

    Sup_cat_ID INT  ,
    Category_Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (Category_ID),
    FOREIGN KEY (Sup_cat_ID) REFERENCES Product(Category_ID)
);
INSERT INTO Category(Category_Name) VALUE('Mustard');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Snack foods');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Paper Goods');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('Bottled waters');
INSERT INTO Category(Category_Name) VALUES('Flowers');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Frozen foods');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Diet foods');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Tomato sauce');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Decorations');
INSERT INTO Category(Category_Name) VALUES('Diet foods');
INSERT INTO Category(Category_Name) VALUES('Alcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Medicines');
INSERT INTO Category(Category_Name) VALUES('Mustard');
INSERT INTO Category(Category_Name) VALUES('Toys');
INSERT INTO Category(Category_Name) VALUES('Salmon');
INSERT INTO Category(Category_Name) VALUES('Baby-care');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('House-cleaning products');
INSERT INTO Category(Category_Name) VALUES('Cereals');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Frozen foods');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Baby-care');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Bread');
INSERT INTO Category(Category_Name) VALUES('Grooming products');
INSERT INTO Category(Category_Name) VALUES('Toys');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('Flowers');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Dishware');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Coffee');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('Candies');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Poultry');
INSERT INTO Category(Category_Name) VALUES('Paper Goods');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Personal hygiene');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Pet foods');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Grooming products');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Cereals');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Tea');
INSERT INTO Category(Category_Name) VALUES('Salmon');
INSERT INTO Category(Category_Name) VALUES('Tea');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Candies');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Vegetables');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Decorations');
INSERT INTO Category(Category_Name) VALUES('Alcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Salmon');
select * from category;