-- Admin data insertion

insert into Admin (Admin_Password) values ('opDAD6hbh');
insert into Admin (Admin_Password) values ('wKNGCZ');
insert into Admin (Admin_Password) values ('GpxnTLRl');
insert into Admin (Admin_Password) values ('dYdqJkS9P');
insert into Admin (Admin_Password) values ('Z8ilXVHV');
insert into Admin (Admin_Password) values ('L0XZDcJksmFp');
insert into Admin (Admin_Password) values ('0VMEQP');
insert into Admin (Admin_Password) values ('xwmMqCXsnX');
insert into Admin (Admin_Password) values ('EutuB7');
insert into Admin (Admin_Password) values ('Va9WoZ7n6');


-- Product data insertion
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Tarragon - Primerba, Paste', '1841', 2, '100', '0', 2);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Appetizer - Mango Chevre', '65527', 3, '100', '0', 3);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Quail - Whole, Boneless', '03', 4, '100', '0', 4);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Beef Dry Aged Tenderloin Aaa', '6', 5, '100', '0', 5);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Rice - Aborio', '6', 6, '100', '0', 6);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Versatainer Nc - 8288', '8722', 7, '100', '0', 7);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Spoon - Soup, Plastic', '3', 8, '100', '0', 8);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Fish - Artic Char, Cold Smoked', '5', 9, '100', '0', 9);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Lettuce - Spring Mix', '38', 10, '100', '0', 10);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Chocolate - Dark Callets', '05', 11, '100', '0', 11);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cabbage - Nappa', '86572', 12, '100', '0', 12);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Ginsing - Fresh', '75', 13, '100', '0', 13);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bread - Pita', '6385', 14, '100', '0', 14);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Octopus - Baby, Cleaned', '6', 15, '100', '0', 15);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Lemonade - Black Cherry, 591 Ml', '7', 16, '100', '0', 16);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Breadfruit', '0124', 17, '100', '0', 17);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Praline Paste', '2', 18, '100', '0', 18);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Paper Cocktail Umberlla 80 - 180', '418', 19, '100', '0', 19);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Lamb Shoulder Boneless Nz', '2675', 20, '100', '0', 20);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Milk Powder', '499', 21, '100', '0', 21);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Sour Puss - Tangerine', '3', 22, '100', '0', 22);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Tuna - Loin', '981', 23, '100', '0', 23);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cheese - Victor Et Berthold', '62276', 24, '100', '0', 24);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Onion Powder', '032', 25, '100', '0', 25);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Wine - Barolo Fontanafredda', '69716', 26, '100', '0', 26);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Table Cloth 62x120 White', '717', 27, '100', '0', 27);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cream - 35%', '635', 28, '100', '0', 28);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Munchies Honey Sweet Trail Mix', '875', 29, '100', '0', 29);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Pork - Backs - Boneless', '07', 30, '100', '0', 30);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Chip - Potato Dill Pickle', '07788', 31, '100', '0', 31);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bacon Strip Precooked', '3664', 32, '100', '0', 32);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bread Crumbs - Japanese Style', '061', 33, '100', '0', 33);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cheese - Comte', '010', 34, '100', '0', 34);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Container - Foam Dixie 12 Oz', '083', 35, '100', '0', 35);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Chinese Foods - Chicken Wing', '0020', 36, '100', '0', 36);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cake - Box Window 10x10x2.5', '4', 37, '100', '0', 37);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Napkin - Beverage 1 Ply', '401', 38, '100', '0', 38);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Plaintain', '96863', 39, '100', '0', 39);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Lobster - Base', '59', 40, '100', '0', 40);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Chinese Foods - Chicken Wing', '4471', 41, '100', '0', 41);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Quail - Jumbo', '3', 42, '100', '0', 42);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Beef - Tongue, Fresh', '3', 43, '100', '0', 43);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Passion Fruit', '6385', 44, '100', '0', 44);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cornflakes', '977', 45, '100', '0', 45);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Garlic - Primerba, Paste', '23536', 46, '100', '0', 46);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Tart - Raisin And Pecan', '95', 47, '100', '0', 47);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Oregano - Fresh', '33', 48, '100', '0', 48);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Sausage - Andouille', '53', 49, '100', '0', 49);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Calypso - Lemonade', '5', 50, '100', '0', 50);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bread - Italian Sesame Poly', '730', 51, '100', '0', 51);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Pasta - Spaghetti, Dry', '86129', 52, '100', '0', 52);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Venison - Striploin', '530', 53, '100', '0', 53);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Sugar - Invert', '2', 54, '100', '0', 54);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Juice - Orange', '90780', 55, '100', '0', 55);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Corn Syrup', '58343', 56, '100', '0', 56);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Pastry - Mini French Pastries', '623', 57, '100', '0', 57);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Skirt - 29 Foot', '7257', 58, '100', '0', 58);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Wine - Balbach Riverside', '18513', 59, '100', '0', 59);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Chicken - Livers', '04', 60, '100', '0', 60);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Table Cloth 62x120 Colour', '4835', 61, '100', '0', 61);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cheese - Ricotta', '7175', 62, '100', '0', 62);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Beans - Butter Lrg Lima', '0', 63, '100', '0', 63);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Veal - Brisket, Provimi,bnls', '7', 64, '100', '0', 64);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Champagne - Brights, Dry', '27', 65, '100', '0', 65);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Taro Leaves', '6', 66, '100', '0', 66);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Gatorade - Orange', '1517', 67, '100', '0', 67);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bandage - Fexible 1x3', '40520', 68, '100', '0', 68);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('External Supplier', '080', 69, '100', '0', 69);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Tomatoes - Cherry, Yellow', '9', 70, '100', '0', 70);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Schnappes Peppermint - Walker', '1', 71, '100', '0', 71);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Plate Pie Foil', '6', 72, '100', '0', 72);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Shrimp - Prawn', '24', 73, '100', '0', 73);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Bread - Sour Sticks With Onion', '53', 74, '100', '0', 74);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Compound - Rum', '03930', 75, '100', '0', 75);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Calypso - Pineapple Passion', '3658', 76, '100', '0', 76);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Dooleys Toffee', '4', 77, '100', '0', 77);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Appetizer - Spring Roll, Veg', '348', 78, '100', '0', 78);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Extract - Almond', '282', 79, '100', '0', 79);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Pepper - Green', '69018', 80, '100', '0', 80);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('The Pop Shoppe - Root Beer', '145', 81, '100', '0', 81);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Thyme - Lemon, Fresh', '9', 82, '100', '0', 82);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('French Pastry - Mini Chocolate', '36220', 83, '100', '0', 83);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Duck - Fat', '0', 84, '100', '0', 84);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Buttons', '05', 85, '100', '0', 85);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Pepper - Cayenne', '29083', 86, '100', '0', 86);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Vinegar - White', '11684', 87, '100', '0', 87);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Asparagus - Green, Fresh', '8', 88, '100', '0', 88);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Truffle Cups - Brown', '801', 89, '100', '0', 89);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Syrup - Golden, Lyles', '0516', 90, '100', '0', 90);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cotton Wet Mop 16 Oz', '2', 91, '100', '0', 91);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Red Cod Fillets - 225g', '95', 92, '100', '0', 92);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Butter - Salted, Micro', '65', 93, '100', '0', 93);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cake Circle, Foil, Scallop', '8334', 94, '100', '0', 94);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Island Oasis - Banana Daiquiri', '9769', 95, '100', '0', 95);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Sprouts - Alfalfa', '80', 96, '100', '0', 96);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Sauce - Cranberry', '49', 97, '100', '0', 97);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Lobster - Canned Premium', '3392', 98, '100', '0', 98);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Cabbage Roll', '31', 99, '100', '0', 99);
INSERT INTO Product (Product_Name, Product_Quantity, Category_ID, Product_Price, Product_Offer, Product_ID) VALUE ('Milk - 2% 250 Ml', '4955', 100, '100', '0', 100);


-- Category data insertion
INSERT INTO Category(Category_Name) VALUE('Mustard');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Snack foods');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Paper Goods');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('Bottled waters');
INSERT INTO Category(Category_Name) VALUES('Flowers');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Frozen foods');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Diet foods');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Tomato sauce');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Decorations');
INSERT INTO Category(Category_Name) VALUES('Diet foods');
INSERT INTO Category(Category_Name) VALUES('Alcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Medicines');
INSERT INTO Category(Category_Name) VALUES('Mustard');
INSERT INTO Category(Category_Name) VALUES('Toys');
INSERT INTO Category(Category_Name) VALUES('Salmon');
INSERT INTO Category(Category_Name) VALUES('Baby-care');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('House-cleaning products');
INSERT INTO Category(Category_Name) VALUES('Cereals');
INSERT INTO Category(Category_Name) VALUES('Flour');
INSERT INTO Category(Category_Name) VALUES('Frozen foods');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Baby-care');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Hygiene products');
INSERT INTO Category(Category_Name) VALUES('Bread');
INSERT INTO Category(Category_Name) VALUES('Grooming products');
INSERT INTO Category(Category_Name) VALUES('Toys');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('Flowers');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Fish');
INSERT INTO Category(Category_Name) VALUES('Dishware');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Coffee');
INSERT INTO Category(Category_Name) VALUES('Seafood');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('Candies');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Cosmetics');
INSERT INTO Category(Category_Name) VALUES('Poultry');
INSERT INTO Category(Category_Name) VALUES('Paper Goods');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Personal hygiene');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Sauces');
INSERT INTO Category(Category_Name) VALUES('White rice');
INSERT INTO Category(Category_Name) VALUES('Pet foods');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Grooming products');
INSERT INTO Category(Category_Name) VALUES('Personal Care');
INSERT INTO Category(Category_Name) VALUES('Cereals');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Pasta');
INSERT INTO Category(Category_Name) VALUES('Tea');
INSERT INTO Category(Category_Name) VALUES('Salmon');
INSERT INTO Category(Category_Name) VALUES('Tea');
INSERT INTO Category(Category_Name) VALUES('Detergents');
INSERT INTO Category(Category_Name) VALUES('Candies');
INSERT INTO Category(Category_Name) VALUES('Sweets');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Vegetables');
INSERT INTO Category(Category_Name) VALUES('Dairy');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Canned Goods');
INSERT INTO Category(Category_Name) VALUES('Decorations');
INSERT INTO Category(Category_Name) VALUES('Alcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Nonalcoholic beverages');
INSERT INTO Category(Category_Name) VALUES('Condiments');
INSERT INTO Category(Category_Name) VALUES('Baby food');
INSERT INTO Category(Category_Name) VALUES('Meat');
INSERT INTO Category(Category_Name) VALUES('Salmon');


-- Cart data insertion
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5160.900662763,6,85);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4639.27070992406,1,54);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6873.10286901198,2,63);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2813.56795103269,6,82);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4558.43644877776,9,2);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7302.07814864119,3,10);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3663.61097441456,6,15);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4052.57185867921,9,55);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8502.31426349437,8,36);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2432.27913617589,9,80);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4952.43623442922,10,81);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7599.73372584057,5,37);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5297.95236289639,5,46);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7934.98807659372,8,44);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7259.29503766601,7,85);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8686.88458247384,2,12);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4786.53846008961,12,96);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(152.034556520188,9,18);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8624.82542598891,8,30);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4191.35846721956,5,63);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2833.03540290707,9,45);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2818.1595512457,11,86);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8137.11475010035,9,94);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7879.72104360849,14,61);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3027.54352148554,5,22);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9477.36056931939,5,50);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3740.1132844552,9,96);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4703.20648502894,1,37);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9629.85855008283,8,83);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2721.68064719517,12,32);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7840.92380809175,3,90);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4059.63013377023,6,15);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8891.9069824223,14,87);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(208.110599326487,10,92);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6840.11717369133,2,17);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5573.78637073272,6,61);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(959.261152619618,14,93);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(1514.10303426865,5,62);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7099.01843421954,7,3);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2072.45086931179,2,74);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7244.46074130175,2,56);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2151.14311207698,5,85);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(1736.64678240458,3,16);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6018.66500582577,11,99);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5320.54603764533,12,15);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6448.45942703516,14,78);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5684.36924092722,3,1);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6731.66090353609,11,24);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(278.334959170937,7,10);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7074.82835012108,6,95);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9145.13288591063,11,50);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9538.18348976419,1,5);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2566.43973791573,7,66);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6463.94450657253,2,27);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4707.29277085759,14,84);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9773.34411107811,3,51);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9312.91608681898,2,27);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2209.66510302418,5,70);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(1539.85165329969,4,51);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7037.48526983358,12,39);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3489.12078989536,11,24);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(1689.05428739872,9,9);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2359.17902484591,9,42);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8334.54615803787,14,57);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9537.24293482501,9,4);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(563.753430220184,12,59);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(1495.78821129342,8,79);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7143.58700031023,8,98);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(4604.60995274159,7,85);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5983.9457454588,5,87);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3292.04374823395,1,5);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(392.875484605262,13,61);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8761.65973397841,8,46);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9118.7945932405,5,59);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2967.15419508803,2,38);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5470.79212018232,6,65);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6176.6403433013,14,23);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(491.118875757381,14,1);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8991.69645114229,10,2);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7225.78212083913,8,28);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9179.89949388658,13,6);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(287.100542428484,2,66);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(2813.90142258951,8,44);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8618.96300840423,5,54);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6746.38192522125,6,40);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(9212.64682332643,8,75);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6876.55034312957,8,22);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(861.316013260892,13,51);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(6018.80984601649,7,65);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(8736.3145042799,9,52);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5666.28838696437,14,15);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5590.52799545905,3,93);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3664.17127405767,5,34);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3579.15343889182,5,27);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(3408.16121773243,6,48);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5389.85827685327,9,96);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(284.045169327895,12,6);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(5001.68246254496,10,36);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7616.90705647408,12,63);
INSERT INTO Cart(Cart_Total_Price, Cart_Product_Quantity, Cart_Product_ID) VALUES(7046.41082045269,3,16);




-- Customer data insertion
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Adina','Leslie',458,'Emden   Walk','Kansas','Escondido',506320,'8-487-503-4517','Adina_Leslie6417@d9un8.info',14);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Caitlyn','Willis',236,'Thomas Doyle   Street','New York','Quebec',508602,'0-735-211-3245','Caitlyn_Willis5627@dbxli.business',40);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Oliver','Simmons',994,'Badric  Alley','Texas','Madison',493687,'7-407-032-3447','Oliver_Simmons7283@c2nyu.press',21);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Savannah','Nelson',423,'Blore  Way','Idaho','Kansas City',720627,'5-527-463-3306','Savannah_Nelson8838@avn7d.pro',33);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Josephine','Armstrong',187,'Westcott  Street','South Dakota','New York',798842,'1-515-337-2221','Josephine_Armstrong4412@dvqq2.ca',94);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Macy','Woods',420,'Virginia Vale','Delaware','Albuquerque',797114,'1-464-484-8645','Macy_Woods8889@nb44i.com',97);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Natalie','Hill',671,'College  Alley','Oklahoma','Cincinnati',841294,'1-306-225-7333','Natalie_Hill8968@ds59r.shop',83);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Harvey','Dyson',776,'Cardinal Crossroad','Oregon','Laredo',460699,'4-346-635-2682','Harvey_Dyson1120@yfxpw.meet',59);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Rocco','Graham',559,'Wakley   Route','North Dakota','Garland',845120,'5-307-108-1152','Rocco_Graham9142@dbxli.host',19);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Boris','Spencer',221,'Buttonwood Alley','South Carolina','St. Louis',157754,'6-271-400-3051','Boris_Spencer3172@crzq7.services',18);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Julia','Dwyer',928,'Buttonwood Grove','South Dakota','Phoenix',892157,'4-432-856-7080','Julia_Dwyer8212@v1wn5.meet',61);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Rose','Widdows',827,'Chestnut  Walk','Alabama','Irving',898532,'8-368-785-0585','Rose_Widdows380@d9un8.zone',43);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Piper','Ainsworth',317,'Coleman  Pass','Pennsylvania','Miami',314122,'4-664-750-5743','Piper_Ainsworth5005@karnv.meet',7);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Nate','Lindsay',270,'Vincent  Alley','Idaho','Saint Paul',915111,'4-214-521-4844','Nate_Lindsay511@yahoo.website',18);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Leslie','Benson',284,'Catherine  Boulevard','Hawaii','Dallas',221179,'1-106-111-8178','Leslie_Benson5736@3wbkp.media',3);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Lucas','Booth',559,'Andrews  Boulevard','Rhode Island','San Bernardino',294465,'7-130-345-5503','Lucas_Booth4912@iscmr.solutions',39);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Bryon','Donnelly',906,'Monroe Vale','Montana','Cincinnati',439865,'8-654-327-1277','Bryon_Donnelly476@dbxli.digital',58);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Analise','Villiger',928,'Apostle  Vale','Georgia','Salem',972105,'4-607-130-2300','Analise_Villiger6815@gkvds.us',18);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Zara','Eastwood',292,'Bolton  Way','Pennsylvania','Fayetteville',364951,'8-216-641-4460','Zara_Eastwood7309@voylg.digital',7);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Jules','Walsh',688,'Aspen Lane','Oklahoma','Cincinnati',205876,'1-408-263-0567','Jules_Walsh8381@cke3u.store',61);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Harriet','Greenwood',306,'Meadow Alley','New Mexico','Jersey City',302066,'0-360-633-0504','Harriet_Greenwood1730@xqj6f.club',13);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Dalia','Archer',206,'Walnut Street','Washington','Sacramento',488802,'8-682-540-6277','Dalia_Archer9643@lhp4j.store',42);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Lillian','Clark',351,'Enderby   Pass','Indiana','Atlanta',619024,'4-471-270-7621','Lillian_Clark9736@hepmv.design',39);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tyler','Fowler',924,'Cobden  Boulevard','Wyoming','Los Angeles',172224,'4-783-846-4136','Tyler_Fowler1478@bu2lo.catering',44);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Matthew','Grant',338,'Virginia Alley','New Mexico','San Bernardino',396888,'3-208-472-3775','Matthew_Grant4796@karnv.net',93);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Owen','Powell',786,'Clarges   Boulevard','Washington','Springfield',225590,'3-483-800-0858','Owen_Powell7153@nmz0p.zone',96);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Percy','Chappell',426,'Chancellor  Tunnel','Ohio','Rome',180994,'0-103-678-1785','Percy_Chappell29@bcfhs.space',46);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Kurt','Oswald',537,'Chestnut Rise Rue','Utah','Bridgeport',946750,'6-388-757-3872','Kurt_Oswald7834@ohqqh.mobi',40);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Phillip','Wise',918,'Hickory   Alley','Ohio','London',301843,'8-506-423-7405','Phillip_Wise2623@zynuu.site',30);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Gil','Hudson',115,'Linden Way','South Dakota','Dallas',252227,'1-258-207-6060','Gil_Hudson2202@d9un8.us',90);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Lorraine','Redden',384,'Kinglake  Drive','Minnesota','London',641416,'4-647-815-2075','Lorraine_Redden1976@p5emz.media',54);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Crystal','Chapman',304,'Elf  Road','Arkansas','Anaheim',977726,'3-361-351-8883','Crystal_Chapman6007@y96lx.digital',82);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tony','Stone',287,'Betton  Avenue','South Carolina','Huntsville',906573,'7-870-825-3044','Tony_Stone6012@6ijur.online',89);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Mason','Uttridge',372,'Cephas  Alley','Massachusetts','Glendale',241896,'0-382-784-5373','Mason_Uttridge4389@jh02o.us',9);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Lucas','Saunders',565,'Jackson Hill','Washington','Seattle',762737,'7-707-317-8050','Lucas_Saunders5060@mpibr.works',54);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Bart','Wilcox',268,'Hickory   Road','New Mexico','Murfreesboro',613890,'4-631-375-7023','Bart_Wilcox321@zynuu.mobi',24);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Henry','Fulton',423,'Westcott  Road','Montana','Escondido',216086,'3-386-076-3242','Henry_Fulton7079@dbxli.net',50);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Deborah','Pitt',524,'Sheringham   Crossroad','Wisconsin','Long Beach',463680,'5-845-024-8326','Deborah_Pitt897@zynuu.services',80);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Michael','Shelton',739,'Bury  Boulevard','Georgia','Atlanta',468994,'8-017-012-8051','Michael_Shelton1177@ag5wi.digital',30);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Maggie','Ranks',368,'Cleveland  Drive','Vermont','Louisville',282539,'3-247-780-0306','Maggie_Ranks9945@dvqq2.net',84);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Eileen','Alexander',178,'Apostle  Rue','New Jersey','Fullerton',559799,'6-638-283-4683','Eileen_Alexander8821@ds59r.ca',14);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Peter','Allington',732,'Biggerstaff   Boulevard','Maine','Philadelphia',371505,'4-042-214-6200','Peter_Allington995@d9un8.biz',83);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Ron','Bullock',373,'Balham   Street','Massachusetts','Omaha',558379,'5-075-861-3703','Ron_Bullock1492@6ijur.biz',19);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Russel','Bailey',652,'Collins  Route','Connecticut','Berna',364544,'2-240-060-5405','Russel_Bailey2611@3wbkp.org',75);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Clarissa','Wright',335,'Gautrey  Walk','New Jersey','Norfolk',546301,'0-664-381-5543','Clarissa_Wright6969@yahoo.website',41);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Colleen','Fox',669,'Jackson Hill','Hawaii','Kansas City',627442,'8-176-684-5200','Colleen_Fox2475@gnjps.page',25);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Josh','Verdon',677,'Amwell    Avenue','Oregon','Jersey City',738996,'2-040-058-1514','Josh_Verdon2247@voylg.ca',80);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Colleen','Locke',453,'Baylis  Alley','Wyoming','Innsbruck',497460,'4-044-230-8703','Colleen_Locke6818@iaart.ca',51);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Leilani','Preston',721,'Cheney  Road','Connecticut','Valetta',478421,'2-876-505-0704','Leilani_Preston9852@uagvw.solutions',84);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tyler','Uttridge',418,'Battersea   Road','Minnesota','Boston',592741,'2-511-443-4502','Tyler_Uttridge3078@chkzl.center',26);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Hope','Rothwell',846,'Ayres   Drive','Georgia','Otawa',657271,'0-463-623-1623','Hope_Rothwell40@jh02o.ca',63);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Goldie','Howard',391,'Caxton  Street','Georgia','Phoenix',666590,'3-456-275-7840','Goldie_Howard9845@p5emz.directory',84);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Matthew','Campbell',590,'Belmont Park Alley','Virginia','Bucharest',978474,'5-370-163-4700','Matthew_Campbell1705@fhuux.website',83);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Samantha','Purvis',144,'Lincoln Route','Colorado','Sacramento',679147,'1-810-835-0450','Samantha_Purvis8565@evyvh.autos',59);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Britney','Andersson',259,'Earl Rise Lane','South Dakota','Sacramento',224600,'2-544-165-0617','Britney_Andersson2170@nb44i.pro',56);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Bob','Morrison',702,'Jackson Avenue','Ohio','Las Vegas',246907,'8-717-406-4206','Bob_Morrison4152@gnjps.site',88);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Leilani','Webster',173,'Tisbury  Rue','New Hampshire','Anaheim',806881,'8-708-055-2534','Leilani_Webster3497@nmz0p.auction',54);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tyson','Richards',904,'Cleveland  Hill','California','Indianapolis',523494,'0-783-804-5237','Tyson_Richards6576@gnjps.meet',45);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Hazel','Bradshaw',830,'Blomfield  Hill','Georgia','Long Beach',403538,'4-332-402-7357','Hazel_Bradshaw1515@bqkv0.info',44);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Violet','Waterson',200,'Carltoun   Crossroad','Oklahoma','Hayward',707842,'8-100-278-4458','Violet_Waterson5537@fhuux.club',13);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Macy','Shelton',350,'Tilloch   Crossroad','Iowa','Hollywood',315216,'0-265-324-5462','Macy_Shelton2613@yvu30.website',51);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Carina','Isaac',666,'Eaglet  Tunnel','Oklahoma','Hayward',652229,'7-887-547-6270','Carina_Isaac97@voylg.works',12);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tony','Page ',131,'Littlebury  Drive','Alabama','Salt Lake City',162185,'4-654-688-1407','Tony_Page 4450@3wbkp.mobi',4);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tom','Saunders',124,'Blean   Road','Wisconsin','San Francisco',474562,'2-380-785-8773','Tom_Saunders8425@1kmd3.works',2);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Cedrick','Exton',557,'Rivervalley Grove','South Dakota','Berlin',565203,'1-083-780-0312','Cedrick_Exton3070@gnjps.catering',28);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Peter','Morgan',615,'Clyde Tunnel','Kansas','Ontario',697627,'5-620-828-5437','Peter_Morgan8162@gnjps.info',7);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Stephanie','Edwards',492,'Calverley  Drive','South Carolina','Valetta',970084,'6-854-032-0827','Stephanie_Edwards1592@ds59r.name',2);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Maxwell','Parker',874,'Blake  Alley','Florida','Irving',335255,'7-568-636-7223','Maxwell_Parker886@bqkv0.property',47);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Bristol','Whinter',878,'Under  Route','Nevada','Escondido',796809,'2-242-787-1225','Bristol_Whinter4579@ds59r.store',26);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Martin','Chester',893,'Camdale  Way','Hawaii','Valetta',726857,'2-722-508-8385','Martin_Chester4327@lyvnc.online',1);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Juliette','Johnson',866,'Charnwood   Lane','Rhode Island','Springfield',948441,'4-283-081-3870','Juliette_Johnson444@ckzyi.media',62);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Havana','Lee',194,'Virginia Way','Nebraska','Hayward',309197,'8-474-007-2337','Havana_Lee3436@uagvw.autos',94);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Denis','Torres',556,'Blackpool  Route','Massachusetts','Houston',951094,'4-582-862-6363','Denis_Torres5140@ohqqh.audio',32);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Bart','Stone',697,'Bales  Pass','Arizona','Fort Lauderdale',885961,'6-673-277-0688','Bart_Stone4100@ohqqh.autos',35);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Ember','Wright',911,'Zealand Street','Indiana','Long Beach',279850,'8-585-242-2405','Ember_Wright2050@yfxpw.business',38);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Emma','Anderson',786,'Camley   Rue','Nevada','Portland',544084,'3-025-376-2353','Emma_Anderson7147@bcfhs.info',74);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Johnathan','Thorne',898,'King Drive','California','Sacramento',154151,'6-237-514-0632','Johnathan_Thorne2419@ag5wi.mobi',86);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Lorraine','Lewis',850,'Camdale  Hill','South Dakota','Lancaster',754604,'5-448-074-2317','Lorraine_Lewis484@iaart.software',60);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Aurelia','Bentley',944,'Collingwood  Drive','Wisconsin','Norfolk',166597,'7-156-224-0652','Aurelia_Bentley1509@urn0m.website',1);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Piper','Bishop',863,'Elf  Pass','Mississippi','Kansas City',638200,'6-521-606-0430','Piper_Bishop8120@yahoo.software',96);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Phillip','Casey',396,'Waldram Park  Avenue','New Mexico','Orlando',528770,'3-050-572-0088','Phillip_Casey6614@ohqqh.video',35);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Josh','Plant',651,'Duthie   Hill','Kansas','Phoenix',187386,'8-738-430-2176','Josh_Plant7171@hepmv.meet',42);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Deborah','Walsh',824,'Belmore  Walk','Maine','Bucharest',344526,'4-582-718-1240','Deborah_Walsh8701@xqj6f.video',57);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Mabel','Warden',534,'Chelsea Manor  Way','Tennessee','Memphis',212631,'7-824-332-6714','Mabel_Warden8208@xqj6f.press',42);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Ema','Walsh',454,'Spruce Pass','Michigan','Albuquerque',700374,'3-130-765-7374','Ema_Walsh8748@zynuu.video',83);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Brad','Flett',177,'King William  Lane','Texas','Kansas City',165311,'2-331-233-2651','Brad_Flett2090@uagvw.info',87);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Adeline','Lane',473,'Caldwell   Route','Michigan','Salem',520044,'6-453-486-6826','Adeline_Lane3945@yahoo.media',58);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Chad','Craig',221,'Parkfields Tunnel','Tennessee','San Bernardino',150165,'3-062-356-7183','Chad_Craig7513@jcf8v.host',79);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Manuel','Murphy',313,'Battis   Grove','Florida','San Antonio',129434,'0-311-301-0548','Manuel_Murphy4532@v1wn5.edu',35);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Rosie','Horton',278,'Vincent  Alley','Nebraska','Paris',550832,'3-337-305-8161','Rosie_Horton9206@xqj6f.page',37);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Amy','Isaac',209,'Chelsea Manor  Drive','Pennsylvania','San Diego',378516,'0-714-248-2256','Amy_Isaac584@fhuux.video',69);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Tom','Rust',327,'Lonsdale  Route','Indiana','Amarillo',108220,'5-046-684-0706','Tom_Rust5205@gnjps.design',68);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Matthew','Thomas',718,'Tiptree   Crossroad','Maine','Atlanta',460304,'5-538-008-6818','Matthew_Thomas2542@evyvh.info',55);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Percy','Lewin',333,'Earl Rise Way','Wyoming','Scottsdale',867689,'3-574-611-2410','Percy_Lewin1081@y96lx.mobi',98);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Sofie','Mcguire',639,'West Street','Indiana','Phoenix',594774,'2-351-076-4045','Sofie_Mcguire5169@cke3u.video',93);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Aileen','Welsch',749,'Chantry   Alley','New Mexico','Baltimore',536520,'6-445-576-8821','Aileen_Welsch3907@nanoff.directory',23);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Florence','Gosling',184,'Heritage Road','Florida','Scottsdale',789244,'1-774-674-7414','Florence_Gosling5846@3wbkp.info',90);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Rocco','Wellington',664,'Timber   Vale','Michigan','Innsbruck',105127,'3-044-363-1763','Rocco_Wellington7227@yvu30.website',22);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Morgan','Curtis',860,'Buttonwood Avenue','Colorado','St. Louis',251834,'6-813-755-5561','Morgan_Curtis6519@ag5wi.business',53);
INSERT INTO Customer(Customer_First_Name, Customer_Last_Name, Customer_Address_BuildingNo, Customer_Address_Street, Customer_Address_City, Customer_Address_State, Customer_Address_Pincode, Customer_Contact_Number, Customer_Email, Customer_Cart_ID) VALUES('Matthew','Hope',729,'Durham Pass','Kansas','Laredo',732170,'3-417-684-6636','Matthew_Hope4591@chkzl.digital',36);
